[workspace]
members = [".", "java-ast-parser"]

[package]
name = "java-to-pyi"
version = "0.1.0"
edition = "2024"

[dependencies]
java-ast-parser = { path = "./java-ast-parser/" }
lalrpop-util = "0.22.2"
topo_sort = "0.4.0"
orx-tree = "2.2.0"
